spring:
  rabbitmq:
    host: 10.10.20.22
    port: 5672
    username: cqjxj
    password: cqjxj123
logging:
  config: classpath:logback.xml
---
spring:
  profiles: dev
  sleuth:
    sampler:
      percentage: 1 # 开发环境，收集所有链路的日志
    enabled: true
  zipkin:
    sender:
      type: rabbit