spring:
  rabbitmq:     # 配置RabbitMQ
    host: 10.10.20.22
    port: 5672
    username: cqjxj
    password: cqjxj123
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.10.20.22:3306/cqytjgpt?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: ccttic!
    driver-class-name: com.mysql.jdbc.Driver
    initialize: true
    druid:
      initial-size: 1
      max-active: 15
      min-idle: 1
      validation-query: select 1
      validation-query-timeout: 10000
      test-on-borrow: true
      test-while-idle: true
      test-on-return: false
      filters: stat,wall,log4j
      pool-prepared-statements: true
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration: # 配置懒加载机制
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    log-prefix: dao.

logging:
  config: classpath:logback.xml

eureka:
  client:
    healthcheck:
      enabled: true   # 开启健康检测，该配置不能配置在bootstrap.yml中，会出现服务检测异常

# 手动POST刷新配置需要关闭安全策略
management:
  security:
    enabled: false
---
spring:
  profiles: dev
  sleuth:
    sampler:
      percentage: 1 # 开发环境，收集所有链路的日志
    enabled: true
  zipkin:
    sender:
      type: rabbit
      
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000      
#全局配置    
ribbon:
  ReadTimeout: 30000 #请求连接超时 单位毫秒
  ConnectTimeout: 30000 #请求处理超时 单位毫秒            