spring:
  rabbitmq:     # 配置RabbitMQ
    host: 10.10.20.22
    port: 5672
    username: cqjxj
    password: cqjxj123
  mail:
    default-encoding: UTF-8
    host: smtp.exmail.qq.com
    password: 123456
    port: 465
    protocol: smtp
    username: zhuliang@ccttic.com
  redis:
#      host: 127.0.0.1
      host: 10.10.20.22 
      port: 6379
#      database: 2  
  session: 
    store-type: redis # spring session使用存储类型
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.10.20.22:3306/cqytjgpt?useSSL=false&useUnicode=true&characterEncoding=utf-8
#    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: ccttic!
#    password: rootrootipnms
    driver-class-name: com.mysql.jdbc.Driver
    initialize: true
    druid:
      initial-size: 1
      max-active: 15
      min-idle: 1
      validation-query: select 1
      validation-query-timeout: 10000
      test-on-borrow: true
      test-while-idle: true
      test-on-return: false
      filters: stat,wall,log4j
      pool-prepared-statements: true
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration: # 配置懒加载机制
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    log-prefix: dao.

logging:
  config: classpath:logback.xml
  
fdfs:
  so-timeout: 30000
  connect-timeout: 20000 
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 10.10.20.22:22122
  pool:
    #从池中借出的对象的最大数目
    max-total: 153
    #获取连接时的最大等待毫秒数100
    max-wait-millis: 102


eureka:
  client:
    healthcheck:
      enabled: true   # 开启健康检测，该配置不能配置在bootstrap.yml中，会出现服务检测异常

security:
  oauth2:
    resource:
      id: cqytjgpt-web-api
      user-info-uri: http://localhost:10001/user
      prefer-token-info: false       

# 手动POST刷新配置需要关闭安全策略
management:
  security:
    enabled: false
---
spring:
  profiles: dev
  sleuth:
    sampler:
      percentage: 1 # 开发环境，收集所有链路的日志
    enabled: true
  zipkin:
    sender:
      type: rabbit
      
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000      
#全局配置    
ribbon:
  ReadTimeout: 30000 #请求连接超时 单位毫秒
  ConnectTimeout: 30000 #请求处理超时 单位毫秒        