server:
  port: 8083
spring:
  application:
    name: cqytjgpt-hystrix-turbine
  rabbitmq:     # 配置RabbitMQ
    host: 10.10.20.21
    port: 5672
    username: guest
    password: guest
turbine:
  stream:
    port: 8084

# 设置eureka行为
eureka:
  instance:
    instance-id: ${spring.application.name}-${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8090/eureka/

# 手动POST刷新配置需要关闭安全策略
management:
  security:
    enabled: false

info:
  description: 重庆交巡警 源头监管项目 熔断器监控
  server.port: ${server.port}
  management.port: ${turbine.stream.port}
  operation: 请在 http://${spring.cloud.client.ipAddress}:${server.port}/hystrix 中访问 http://${spring.cloud.client.ipAddress}:${turbine.stream.port}/turbine.stream