spring:
  rabbitmq:
    host: 10.10.20.22
    port: 5672
    username: cqjxj
    password: cqjxj123

---
spring:
  profiles: dev
  sleuth:
    enabled: true
    sampler:
      percentage: 1
  zipkin:
    sender:
      type: rabbit