spring:
  session:
    store-type: none  
  rabbitmq:     # 配置RabbitMQ
    host: 10.10.20.21
    port: 5672
    username: guest
    password: guest
  datasource: # 配置数据源
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.10.20.22:3306/quartz?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: ccttic!
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      max-active: 15
      min-idle: 1
      validation-query: select 1
      validation-query-timeout: 10000
      test-on-borrow: true
      test-while-idle: true
      test-on-return: false
      filters: stat,wall,log4j
      pool-prepared-statements: true
      
logging:
  config: classpath:logback.xml
          
#全局配置    
ribbon:
  ReadTimeout: 10000 #请求连接超时 单位毫秒
  ConnectTimeout: 10000 #请求处理超时 单位毫秒
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: true 
      
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 80000
            
# 手动POST刷新配置需要关闭安全策略
management:
  security:
    enabled: false
                
eureka:
  client:
    healthcheck:
      enabled: true   # 开启健康检测，该配置不能配置在bootstrap.yml中，会出现服务检测异常