spring:
  session:
    store-type: none  
  rabbitmq:     # 配置RabbitMQ
    host: 10.10.20.22
    port: 5672
    username: cqjxj
    password: cqjxj123
  datasource: # 配置数据源
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.10.20.22:3306/quartz?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: ccttic!
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      max-active: 15
      min-idle: 1
      validation-query: select 1
      validation-query-timeout: 10000
      test-on-borrow: true
      test-while-idle: true
      test-on-return: false
      filters: stat,wall,log4j
      pool-prepared-statements: true
      