spring:
  rabbitmq:   # 配置rabbitMQ
    host: 10.10.20.22
    port: 5672
    username: cqjxj
    password: cqjxj123
  datasource: # 配置数据源
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.10.20.22:3306/cqytjgpt
    username: root
    password: ccttic!
    driver-class-name: com.mysql.jdbc.Driver
    initialize: true
    druid:
      initial-size: 1
      max-active: 15
      min-idle: 1
      validation-query: select 1
      validation-query-timeout: 10000
      test-on-borrow: true
      test-while-idle: true
      test-on-return: false
      filters: stat,wall,log4j
      pool-prepared-statements: true
# mybatis 配置
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:  # 配置懒加载机制
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    log-prefix: dao.
#log 设置
debug:
  true
logging:
  level:
    tk:
      mybatis:
        TRACE
    com:
      ccttic:
        auth:
          trace
  config: classpath:logback.xml